I=imread('coins.png');
figure(1);
subplot(1,2,1);
imshow(I);
title('Source');
[count,x]=imhist(I,64);title('Graph');
[M,N]=size(I);
counts=count/M/N;
subplot(1,2,2);
stem(x,counts);
%增加对比度
O=conversion(I,2,-55);
plot2(O,2,'增强')
